include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/maven-building.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - build
  - package
  - test-package
  - deploy

variables:
  PARENT_IMAGE_NAME: registry.gitlab.com/redmic-project/docker/redmic-server
  PARENT_IMAGE_TAG: latest
  STACK: api
  STATUS_CHECK_DELAY: 300

.docker-operations-build:
  variables:
    DOCKER_BUILD_ARGS: --build-arg PARENT_IMAGE_NAME=${PARENT_IMAGE_NAME} --build-arg PARENT_IMAGE_TAG=${PARENT_IMAGE_TAG}

.deploy:
  script:
    - >
      deploy.sh IMAGE_NAME=${IMAGE_NAME} IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE}
      SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE} SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET} AWS_ACCESS_KEY=${AWS_ACCESS_KEY} AWS_SECRET_KEY=${AWS_SECRET_KEY}
      ELASTIC_XPACKSECURITYUSER=${ELASTIC_XPACKSECURITYUSER} AWS_REGION=${AWS_REGION} S3_BUCKET="${S3_BUCKET}"
      PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}

.deploy-development:
  variables:
    SPRING_PROFILES_ACTIVE: pre
  environment:
    url: https://${PUBLIC_HOSTNAME}/${CI_PROJECT_NAME}

.deploy-production:
  variables:
    SPRING_PROFILES_ACTIVE: prod
  environment:
    url: https://${PUBLIC_HOSTNAME}/${CI_PROJECT_NAME}
