version: '3.5'

services:
  api:
    ports:
      - target: ${MICROSERVICE_PORT}
        published: ${MICROSERVICE_PORT}
        mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 820M

volumes:
  mediastorage-private-vol:
    name: mediastorage-private-vol

  mediastorage-public-vol:
    name: mediastorage-public-vol
