version: '3.5'

services:
  api:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - MICROSERVICE_NAME
      - MICROSERVICE_PORT
      - SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - ELASTIC_XPACKSECURITYUSER
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - elastic-net
      - postgres-net
      - redmic-net
      - traefik-net
    volumes:
      - mediastorage-private-vol:/data/MEDIA_STORAGE
      - mediastorage-public-vol:/data/PUBLIC_MEDIA_STORAGE
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${MICROSERVICE_PORT}/${MICROSERVICE_NAME}/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 4m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.docker.network: traefik-net
        traefik.port: "${MICROSERVICE_PORT}"
        traefik.sitemap.frontend.rule: PathPrefix:/sitemap;AddPrefix:${MICROSERVICE_NAME}
        traefik.sitemap.backend: ${MICROSERVICE_NAME}
        traefik.microservice.frontend.rule: PathPrefix:/${MICROSERVICE_NAME}
        traefik.microservice.backend: ${MICROSERVICE_NAME}
        traefik.mediastorage.frontend.rule: PathPrefix:/${MICROSERVICE_NAME}/mediastorage/photobank/{animals|layers|species|platforms|organisations}
        traefik.mediastorage.frontend.redirect.regex: ^.*/${MICROSERVICE_NAME}/mediastorage/(photobank)/(animals|layers|species|platforms|organisations)/(.+\\.(?:gif|jpe?g|png))$$
        traefik.mediastorage.frontend.redirect.replacement: https://s3-${AWS_REGION}.amazonaws.com/${S3_BUCKET}/public/$$1/$$2/$$3
        traefik.grafcan.frontend.rule: PathPrefix:/grafcan
        traefik.grafcan.frontend.redirect.regex: ^.*/grafcan(.*)$$
        traefik.grafcan.frontend.redirect.replacement: https://visor.grafcan.es/busquedas/toponimoxml$$1
      restart_policy:
        delay: 1m
        window: 3m

networks:
  elastic-net:
    external: true

  postgres-net:
    external: true

  redmic-net:
    external: true

  traefik-net:
    external: true